/*
 * MstatisticsPanel.java
 *
 * Created on 7 Ιούλιος 2009, 1:09 μμ
 */

package gui.Panels;

import graphs.Graph;
import graphs.LayoutMetrics;
import graphs.LayoutMetrics2;
import graphs.MetricsEvaluation;
import java.io.File;
import java.text.DecimalFormat;

/**
 *
 * @author  zabetak
 */
public class MstatisticsPanel extends javax.swing.JPanel {
    private DecimalFormat df = new DecimalFormat("##.###");
    private Graph g;
    /** Creates new form MstatisticsPanel */
    public MstatisticsPanel(Graph graph) {
        initComponents();
        g = graph;
        refreshButton.doClick();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        vImproveField = new javax.swing.JTextField();
        verticalityfield = new javax.swing.JTextField();
        idealVerticalityfield = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        verticalityIButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        idealAreaField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        areaIButton = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        aImproveField = new javax.swing.JTextField();
        areaField = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        kmField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        keField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        applyFDPA = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        iterationField = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        E_field = new javax.swing.JTextField();
        haveSupsField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        haveSubsField = new javax.swing.JTextField();
        N_field = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        maxSubsField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        maxSupsField = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        qualityField = new javax.swing.JSpinner();
        jLabel16 = new javax.swing.JLabel();
        saveButton1 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        noteField = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        exportField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        importField = new javax.swing.JTextField();
        stateSave = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        stateLoad = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        refreshButton = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        kmKeRelation = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Metric Statistics"));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Verticality Metrics"));

        jLabel11.setText("VImprove:");

        vImproveField.setEditable(false);
        vImproveField.setText("IV-V");
        vImproveField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vImproveFieldActionPerformed(evt);
            }
        });

        verticalityfield.setEditable(false);
        verticalityfield.setText("V");

        idealVerticalityfield.setEditable(false);
        idealVerticalityfield.setText("IV");
        idealVerticalityfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idealVerticalityfieldActionPerformed(evt);
            }
        });

        jLabel10.setText("IdealVerticality:");

        verticalityIButton.setText("Improve");
        verticalityIButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verticalityIButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Verticality:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(vImproveField)
                            .addComponent(idealVerticalityfield)
                            .addComponent(verticalityfield, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(verticalityIButton))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(verticalityfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(idealVerticalityfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(vImproveField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(verticalityIButton)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Area Metrics"));

        jLabel13.setText("AImprove:");

        idealAreaField.setEditable(false);
        idealAreaField.setText("IA");
        idealAreaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idealAreaFieldActionPerformed(evt);
            }
        });

        jLabel2.setText("Area:");

        areaIButton.setText("Improve");
        areaIButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areaIButtonActionPerformed(evt);
            }
        });

        jLabel12.setText("Ideal Area:");

        aImproveField.setEditable(false);
        aImproveField.setText("IA-A/...");
        aImproveField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aImproveFieldActionPerformed(evt);
            }
        });

        areaField.setEditable(false);
        areaField.setText("A");
        areaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areaFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(areaIButton)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(96, 96, 96)
                            .addComponent(aImproveField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel13)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(areaField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(idealAreaField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel12))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(areaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(idealAreaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(aImproveField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(areaIButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "FDPA"));

        kmField.setText("Km");

        jLabel7.setText("Km:");

        keField.setText("Ke");

        jLabel6.setText("Ke:");

        applyFDPA.setText("Apply FDPA");
        applyFDPA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyFDPAActionPerformed(evt);
            }
        });

        jLabel18.setText("Iterations:");

        iterationField.setText("Iterations");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(kmField)
                            .addComponent(keField, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE))
                        .addContainerGap(25, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(applyFDPA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(100, 100, 100))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(iterationField, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(keField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(kmField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(iterationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(applyFDPA)
                .addGap(56, 56, 56))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Graph Features"));

        E_field.setEditable(false);
        E_field.setText("E");

        haveSupsField.setEditable(false);
        haveSupsField.setText("-");

        jLabel9.setText("HaveSups:");

        jLabel4.setText("N:");

        jLabel8.setText("HaveSubs:");

        haveSubsField.setEditable(false);
        haveSubsField.setText("-");

        N_field.setEditable(false);
        N_field.setText("N");

        jLabel5.setText("E:");

        maxSubsField.setEditable(false);
        maxSubsField.setText("-");

        jLabel14.setText("MaxSubs:");

        jLabel15.setText("MaxSups:");

        maxSupsField.setEditable(false);
        maxSupsField.setText("-");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(E_field)
                            .addComponent(N_field)
                            .addComponent(haveSupsField)
                            .addComponent(haveSubsField, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(maxSupsField)
                            .addComponent(maxSubsField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(haveSubsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(haveSupsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(N_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(7, 7, 7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(E_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(maxSubsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(maxSupsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Evaluate Graph"));

        qualityField.setModel(new javax.swing.SpinnerNumberModel(10, 0, 10, 1));

        jLabel16.setText("Diagram Quality:");

        saveButton1.setText("Save");
        saveButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButton1ActionPerformed(evt);
            }
        });

        jLabel19.setText("Note:");

        noteField.setText("NO");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(qualityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(noteField, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveButton1)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(qualityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveButton1)
                    .addComponent(jLabel19)
                    .addComponent(noteField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "State Save"));

        exportField.setText("exportNodePositions");

        jLabel3.setText("File:");

        importField.setText("importNodePositions");

        stateSave.setText("Save");
        stateSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stateSaveActionPerformed(evt);
            }
        });

        jLabel17.setText("File:");

        stateLoad.setText("Load");
        stateLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stateLoadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(importField, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stateLoad))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exportField, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stateSave)))
                .addContainerGap(165, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(exportField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stateSave))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(importField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stateLoad))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel4, 0, 176, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 199, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton4.setText("Improve All");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        refreshButton.setText("Refresh");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        jButton5.setText("Auto Starview");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        kmKeRelation.setText("Relate Km-Ke");
        kmKeRelation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kmKeRelationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(refreshButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kmKeRelation)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(refreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(kmKeRelation))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
//    LayoutMetrics lm = g.getLayoutMetrics();
//
//    lm.calculateVerticality();
//    lm.calculateNodeDensity();
//    lm.calculateEdgeDensity();
//
//    double v =  lm.getVerticality();
//    double nd = lm.getNodeDensity();
//    double ed = lm.getEdgeDensity();
//    int     n = lm.get_N_();
//    int     e = lm.get_E_();
//
//    DecimalFormat df = new DecimalFormat("##.###");
//    jTextField1.setText(df.format(v));
//    jTextField2.setText(df.format(nd));
//    jTextField3.setText(df.format(ed));
//    jTextField4.setText(df.format(n));
//    jTextField5.setText(df.format(e));
    g.updateNodes();
    LayoutMetrics2 lm = g.getLayoutMetrics2();

    lm.calculateMetrics();
//    lm.calculateVerticality();
//    lm.calculateVImprove();
//    lm.calculateArea();
//    lm.calculateAImprove();

    double V =  lm.getVerticality();
    double IV = lm.getIdealVerticality();
    double VI = lm.getVImprove();

    double A = lm.getArea();
    double IA = lm.getIdealArea();
    double AI = lm.getAImprove();

    int     n = lm.get_N_();
    int     e = lm.get_E_();
    int     hsb = lm.getHavesubs();
    int     hsp = lm.getHavesups();
    int     mxsb = lm.getMaxSubs();
    int     mxsp = lm.getMaxSups();
    
    verticalityfield.setText(df.format(V));
    idealVerticalityfield.setText(df.format(IV));
    vImproveField.setText(df.format(VI));

    areaField.setText(df.format(A));
    idealAreaField.setText(df.format(IA));
    aImproveField.setText(df.format(AI));
    
//    jTextField3.setText("NO");
    N_field.setText(df.format(n));
    E_field.setText(df.format(e));
    keField.setText(df.format(g.getKe()));
    kmField.setText(df.format(g.getKm()));
    iterationField.setText(df.format(g.getMaxIterations()));
    haveSubsField.setText(df.format(hsb));
    haveSupsField.setText(df.format(hsp));
    maxSubsField.setText(df.format(mxsb));
    maxSupsField.setText(df.format(mxsp));
}//GEN-LAST:event_refreshButtonActionPerformed

private void areaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_areaFieldActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_areaFieldActionPerformed

private void verticalityIButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verticalityIButtonActionPerformed
//    LayoutMetrics2 lm = g.getLayoutMetrics2();
//
//    lm.calculateVerticality();
//    lm.calculateAImprove();
//

    g.applyMagicCorrection("V");
    this.refreshButton.doClick();
//  The following comments are <==> with doClick of refreshButton
//    LayoutMetrics2 lm = g.getLayoutMetrics2();
//    lm.calculateVerticality();
//    lm.calculateAImprove();
//
//    double V =  lm.getVerticality();
//    double A = lm.getAImprove();
//    verticalityfield.setText(df.format(V));
//    areaField.setText(df.format(A));
//    keField.setText(df.format(g.getKm()));
//    kmField.setText(df.format(g.getKe()));
}//GEN-LAST:event_verticalityIButtonActionPerformed

private void areaIButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_areaIButtonActionPerformed
//    LayoutMetrics2 lm = g.getLayoutMetrics2();
//
//    lm.calculateVerticality();
//    lm.calculateAImprove();


    g.applyMagicCorrection("A");
    this.refreshButton.doClick();
//  The following comments are <==> with doClick of refreshButton
//    LayoutMetrics2 lm = g.getLayoutMetrics2();
//    lm.calculateVerticality();
//    lm.calculateAImprove();
//
//    double V =  lm.getVerticality();
//    double A = lm.getAImprove();
//    verticalityfield.setText(df.format(V));
//    areaField.setText(df.format(A));
//    keField.setText(df.format(g.getKm()));
//    kmField.setText(df.format(g.getKe()));
   
}//GEN-LAST:event_areaIButtonActionPerformed

private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    g.applyMagicCorrection("Both");

    LayoutMetrics2 lm = g.getLayoutMetrics2();
//    lm.calculateVerticality();
//    lm.calculateAImprove();
    lm.calculateMetrics();
    double V =  lm.getVerticality();
    double VI = lm.getVImprove();

    double A = lm.getArea();
    double AI = lm.getAImprove();

    verticalityfield.setText(df.format(V));
    vImproveField.setText(df.format(VI));
    areaField.setText(df.format(A));
    aImproveField.setText(df.format(AI));
    keField.setText(df.format(g.getKe()));
    kmField.setText(df.format(g.getKm()));
}//GEN-LAST:event_jButton4ActionPerformed

private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
    MetricsEvaluation mE = new MetricsEvaluation(g);
//    mE.automaticActions("descriptionFile", "outputFile.csv");
    mE.automaticActions("infile.txt", "outputFile.csv", 5);

}//GEN-LAST:event_jButton5ActionPerformed

private void idealVerticalityfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idealVerticalityfieldActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_idealVerticalityfieldActionPerformed

private void vImproveFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vImproveFieldActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_vImproveFieldActionPerformed

private void idealAreaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idealAreaFieldActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_idealAreaFieldActionPerformed

private void aImproveFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aImproveFieldActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_aImproveFieldActionPerformed

private void applyFDPAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyFDPAActionPerformed
    double km = Double.parseDouble(this.kmField.getText().replace(',','.'));
    double ke = Double.parseDouble(this.keField.getText().replace(',','.'));
    int iter = Integer.parseInt(this.iterationField.getText());
    g.setKm(km);
    g.setKe(ke);
    g.setMaxIterations(iter);
    g.forceDirectedPlacement(null,true);
    this.refreshButton.doClick();
}//GEN-LAST:event_applyFDPAActionPerformed

private void saveButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButton1ActionPerformed
    MetricsEvaluation mE = new MetricsEvaluation(g);
    File f = new File("saveMetrics.csv");
    String quality = String.valueOf(qualityField.getModel().getValue());
    String note = noteField.getText();
    mE.saveMetrics(f,quality,note);
}//GEN-LAST:event_saveButton1ActionPerformed

private void stateSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stateSaveActionPerformed
    String saveFileName = exportField.getText();
    File f = new File(saveFileName);
    g.getState().saveNodesPositionInFile(f);
}//GEN-LAST:event_stateSaveActionPerformed

private void stateLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stateLoadActionPerformed
    String loadFileName = importField.getText();
    File f = new File(loadFileName);
    g.getState().restoreNodesPositionFromFile(f);
}//GEN-LAST:event_stateLoadActionPerformed

private void kmKeRelationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kmKeRelationActionPerformed
    MetricsEvaluation me = new MetricsEvaluation(g);
    me.determineKmKeRelation("kmKeRelations.csv", 50, 500000, 50, 100000, 500, 10000000);
}//GEN-LAST:event_kmKeRelationActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField E_field;
    private javax.swing.JTextField N_field;
    private javax.swing.JTextField aImproveField;
    private javax.swing.JButton applyFDPA;
    private javax.swing.JTextField areaField;
    private javax.swing.JButton areaIButton;
    private javax.swing.JTextField exportField;
    private javax.swing.JTextField haveSubsField;
    private javax.swing.JTextField haveSupsField;
    private javax.swing.JTextField idealAreaField;
    private javax.swing.JTextField idealVerticalityfield;
    private javax.swing.JTextField importField;
    private javax.swing.JTextField iterationField;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTextField keField;
    private javax.swing.JTextField kmField;
    private javax.swing.JButton kmKeRelation;
    private javax.swing.JTextField maxSubsField;
    private javax.swing.JTextField maxSupsField;
    private javax.swing.JTextField noteField;
    private javax.swing.JSpinner qualityField;
    private javax.swing.JButton refreshButton;
    private javax.swing.JButton saveButton1;
    private javax.swing.JButton stateLoad;
    private javax.swing.JButton stateSave;
    private javax.swing.JTextField vImproveField;
    private javax.swing.JButton verticalityIButton;
    private javax.swing.JTextField verticalityfield;
    // End of variables declaration//GEN-END:variables

}
